README.md
tap_chargebee/schemas/credit_notes.json
tap_chargebee/streams/__init__.py
tap_chargebee/streams/credit_notes.py

This PR adds a stream for the [Credit Notes](https://apidocs.chargebee.com/docs/api/credit_notes) endpoint through the Chargebee API.

Add Credit Notes Stream

---

LICENSE
README.md
tap_chargebee/schemas/credit_notes.json
tap_chargebee/streams/__init__.py
tap_chargebee/streams/credit_notes.py

Add Credit notes schema to alpha branch

Add credit_notes

---

setup.py
tap_chargebee/schemas/credit_notes.json
tap_chargebee/streams/addons.py
tap_chargebee/streams/base.py
tap_chargebee/streams/coupons.py
tap_chargebee/streams/credit_notes.py
tap_chargebee/streams/customers.py
tap_chargebee/streams/events.py
tap_chargebee/streams/invoices.py
tap_chargebee/streams/payment_sources.py
tap_chargebee/streams/plans.py
tap_chargebee/streams/subscriptions.py
tap_chargebee/streams/transactions.py
tap_chargebee/streams/virtual_bank_accounts.py

This PR updates the Chargebee stream classes to not write invalid fields to the catalog.

Remove Invalid Fields from Stream Discovery

---

tap_chargebee/client.py

This PR removes some error handling code that was leftover from when this got forked from the tap-framework. This code was causing the tap to handle errors incorrectly when an error response code was encountered.

Remove legacy tap framework code

---

setup.py
tap_chargebee/client.py

Noticed a bug in the new error handling logic so I chose to rewrite it using our standard patterns.
- Tested using the Orders stream (which was not enable, and threw a 400 error)
- 

fix retry logic and bump version

---

CHANGELOG.md
setup.py
tap_chargebee/schemas/payment_sources.json

This PR cleans up trailing commas that were missed in the #44 review.
- Ran through a JSON validator and it passed
- Low, version 1.0.2 is not working at this time.
- revert this branch, bump patch version

v1.0.3: Fix invalid json

---

.circleci/config.yml

- Added basic config.yml for CircleCI with virtual environment steps.
- 
- No risk

Add basic config.yml for CircleCI

---

tap_chargebee/schemas/customers.json
tap_chargebee/schemas/events.json

TDL-13343: Investigate transform error in Events stream
- Updated cf_company_id field type for _events_ and _customers_ stream.
- Verified that no error is raised for integer or string value of cf_comapnay_id field for both streams.
- No risk

TDL-13343:Fix transform error in event and customer stream.

---

.circleci/config.yml
tests/base.py
tests/test_chargebee_discovery.py
tests/test_chargebee_pagination.py
tests/test_chargebee_start_date.py
tests/test_chargebee_sync.py

TDL-13802: Added following integration tests suites
- Test Sync Canary
- Test Discovery Mode 
- Test Start Date
- Test Pagination (events stream)
Updated CircleCI config file to include integration tests.
- 
- No risk

TDL-13802 : Add tap tester suites

---

tap_chargebee/__init__.py

- Fix for index out of range issue

case insensitive comparison of site name

---

tests/base.py
tests/test_chargebee_discovery.py
tests/test_chargebee_pagination.py
tests/test_chargebee_start_date.py
tests/test_chargebee_sync.py

TDL-13802: Add tap tester suites
- Updated all integration test suites to cover product catalog versions 1 and 2.
- Integration test is passing in CIrcleCI Build.
- No risk

TDL-13802:Updated integration test to cover product catalog v1 and v2

---

CHANGELOG.md
setup.py

* Remove all minimum/maximum and minLength/maxLength
* Fix JSONDecodeError in Invoices and Transactions streams
* Add Tiersprice attribute
* Updated integration test to cover product catalog v1 and v2
* Add additional fields from API
* Upgraded event stream schema
* Updated Bookmark handling, date without tz will updated in UTC tz format
https://github.com/singer-io/tap-chargebee/pull/45
https://github.com/singer-io/tap-chargebee/pull/51
https://github.com/singer-io/tap-chargebee/pull/53
https://github.com/singer-io/tap-chargebee/pull/63
https://github.com/singer-io/tap-chargebee/pull/64
https://github.com/singer-io/tap-chargebee/pull/57
https://github.com/singer-io/tap-chargebee/pull/54
- tested and compared output vs v1.1.2
- medium

bump v1.2.0

---

CHANGELOG.md
MANIFEST.in
setup.py

This pr adds a manifest to include the schemas directory
- verified that including the manifest includes the schema directory
- low

Add MANIFEST.in

---

CHANGELOG.md
setup.py

bump to v1.3.0
* Added comments stream #52
* Added include_deleted configuration #58
* Added undocumented fields #69
- 
- 

bump v1.3.0

---

CHANGELOG.md
setup.py
tests/base.py
tests/test_chargebee_start_date.py

bump 1.3.1

---

.circleci/config.yml
tap_chargebee/streams/base.py
tests/base.py
tests/test_chargebee_all_fields.py
tests/test_chargebee_automatic_fields.py
tests/test_chargebee_bookmark.py
tests/test_chargebee_discovery.py
tests/test_chargebee_include_delete.py
tests/test_chargebee_pagination.py
tests/test_chargebee_start_date.py
tests/test_chargebee_sync.py

TDL-19099: Add missing tap-tester tests
- Added missing assertion in discovery test
- Added missing tap-tester tests
- All fields test
- Automatic fields test
- Bookmark test
- 
- 

TDL-19099: Add missing tap-tester tests

---

.circleci/config.yml
tap_chargebee/client.py
tests/unittests/test_exception_handling.py
tests/unittests/test_json_decoder_error_handling.py

[TDL-19101](https://jira.talendforge.org/browse/TDL-19101): Add custom exception handling and error logging
- Added customer exception codes map to handle the exception and custom message if message not found in API response.
- Kept retrying mechanism as it is for 4xx and 5xx.
- Verified that exception is raised with a proper error message if a message is present in API response for error.
- Verified that exception is raised with a custom message if API response does not have a message.
- 

TDL-19101: Add custom exception handling

---

tap_chargebee/schemas/item_model/item_families.json
tap_chargebee/schemas/item_model/item_prices.json
tap_chargebee/schemas/item_model/items.json
tests/test_chargebee_all_fields.py

Added custom field support for Item Model entities (items, item_prices and item_families)
Updated integration tests.
- 
- 

Added custom field support for Item Model entities

---

CHANGELOG.md
setup.py

bump patch version 1.3.4
- 
- 

bumped patch version and updated changelog

---

CHANGELOG.md
setup.py

Bump version 1.3.5

---

CHANGELOG.md
setup.py

Minor bump v1.4.0

---

.circleci/config.yml

- Upgrade circleci image
- Swap from pyenv to uv
- Swap from nose to pytest
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code

SAC-28166: CircleCI Upgrade, Swap to UV
